### ISSUE TITLE
Won't build with bam 0.5

### ISSUE THREAD

**Issue by rffontenelle** [SushiTee/teeworlds#10]
Since bam 0.5, this client won't build displaying the following error message:

> $ bam -t release
> [string "src/base.lua"]:38: this file for version 0.4.x of bam. you are running 0.5.x.
> backtrace:
> string "src/base.lua": CheckVersion global
> bam.lua(1): (null) 
> bam: script error (-t for more detail)

This could probably be fixed with a simple cherry-pick from vanilla: https://github.com/teeworlds/teeworlds/commit/d6f3cc159257a2d6033e3ef46906c72c9db1b9eb

**Comment by SushiTee** [comment]
This is right. I saw this but I figured it's not that urgent since you can still use bam 0.4.
Which branch do you want to compile?

**Comment by rffontenelle** [comment]
I'm compiling Client-Pack-0.6. Please notice that any Arch Linux user will have this issue for any of your Teeworlds-fork branches, as it is a rolling-release distribution.

**Comment by SushiTee** [comment]
hopefully fixed by a748595e05c85d19277eb75c70e76356d05c07b3
